### PR TITLE
Various license updates

### PR DESCRIPTION
**Pull request by jw3**
Updating per instructions here https://www.apache.org/legal/src-headers.html

### CODE REVIEW

**Comment by jw3** [comment]
Unit tests have been timing out today.  Not sure why...

**Comment by jw3** [comment]
Thanks @Shanedell

**Comment by arosien** [comment]
My only concern is that these changes are preparation for assignment to Apache, but don't record our own license and copyright (pre-assignment). Do you think that is important?

For instance, I thought this change would list us as the copyright holders, and there would be some subsequent commit during "assignment". But nothing like that is mentioned in the referenced instructions.

**Comment by jw3** [comment]
I think you are right. Will adjust.

**Comment by jw3** [comment]
The snippets file is json... does it get noted in the notices file

**Comment by jw3** [comment]
Im going to merge this so some other work can progress, we can adjust further if needed in separate PR

**Pull request merged**
