### PR TITLE
Use Path/File vs URI to refer to schemas.

### LINKED ISSUE #119: Windows Illegal char ':' for data file path
In a workspace without a launch.json, debugging the xsd file with ctrl+p and selecting the data file shown in the error message.

```
09:30:26.761 [io-compute-2] DEBUG org.apache.daffodil.debugger.dap.Parse - deliverParseData: Errored(java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///c:/Users/wassj/Downloads/test-dfdl-workspace/jpeg.dfdl.xsd)
```

Further up the stack

```
09:30:21.137 [io-compute-0] INFO org.apache.daffodil.debugger.dap.DAPSession - <R #1 initialize success {"supportsConfigurationDoneRequest":true,"supportsHitConditionalBreakpoints":false,"supportsConditionalBreakpoints":false,"supportsEvaluateForHovers":false,"supportsCompletionsRequest":false,"supportsRestartFrame":false,"supportsSetVariable":false,"supportsRestartRequest":false,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":false,"supportsLogPoints":false,"supportsExceptionInfoRequest":false,"supportsDataBreakpoints":false,"supportsClipboardContext":false,"supportsLoadedSourcesRequest":false}
09:30:21.140 [io-compute-2] INFO org.apache.daffodil.debugger.dap.DAPSession - <E initialized
09:30:21.147 [io-compute-1] INFO org.apache.daffodil.debugger.dap.DAPSession - R> #2 launch {"type":"dfdl","name":"Run File","request":"launch","program":"c:\\Users\\wassj\\Downloads\\test-dfdl-workspace\\jpeg.dfdl.xsd","data":"c:\\Users\\wassj\\Downloads\\test-dfdl-workspace\\works.jpg","debugServer":4711,"infosetOutput":{"type":"file","path":"jpeg-infoset.xml"},"__sessionId":"1f794440-be74-438c-9e9d-af41c60b8dbd"}
09:30:21.150 [io-compute-3] INFO org.apache.daffodil.debugger.dap.DAPSession - R> #3 configurationDone null
```

### PR DESCRIPTION
**Pull request by arosien**
Fixes #119.

### CODE REVIEW

**Comment by arosien** [comment]
@jw3 can you try this out?

**Comment by jw3** [comment]
Different error 

```
15:01:53.911 [io-compute-3] DEBUG org.apache.daffodil.debugger.dap.Parse - deliverParseData: Errored(java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/c:/Users/wassj/Downloads/test-dfdl-workspace/jpeg.dfdl.xsd)
```

**Comment by arosien** [comment]
> Different format but errors
> 
> ```
> 15:01:53.911 [io-compute-3] DEBUG org.apache.daffodil.debugger.dap.Parse - deliverParseData: Errored(java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/c:/Users/wassj/Downloads/test-dfdl-workspace/jpeg.dfdl.xsd)
> ```

To be paranoid, are you sure you're using the code from this branch?

**Comment by jw3** [comment]
> To be paranoid, are you sure you're using the code from this branch?

Now you are just trying to scare me.... Let's see...

**Comment by arosien** [comment]
> > To be paranoid, are you sure you're using the code from this branch?
> 
> Now you are just trying to scare me.... Let's see...

There should be a git hash printed as part of the startup of `DAPodil`.

**Comment by jw3** [comment]
I installed https://github.com/jw3/example-daffodil-vscode/releases/tag/v0.0.15-pre4

Which has commits  https://github.com/jw3/example-daffodil-vscode/commits/v0.0.15-pre4

I restarted vs code just to be sure, the extension info page claims 0.0.15-pre4

**Comment by jw3** [comment]
hmm I dont see a git commit id anywhere

**Comment by arosien** [comment]
> hmm I dont see a git commit id anywhere

oh, it's probably not there because you're installing off a tag, sorry

**Comment by arosien** [comment]
@jw3 i pushed a thing to dump a stack trace when that path is hit, can you cut a new release and try it for me?

**Comment by arosien** [comment]
we really need a live chat mechanism... :)

**Comment by arosien** [comment]
Cool, that stack helps. Thanks.

**Comment by arosien** [comment]
The underlying issue is that the DAP session expects sources referred to in stack frames to be paths, not URIs, but our code is supplying URIs because Daffodil uses URIs as their base representation for location of the schema.

**Comment by jw3** [comment]
Good news, the schema looked good, the data file failed

```
InvalidPathException: Illegal char <:> at index 2: /c:/Users/wassj/Downloads/test-dfdl-workspace/jpeg.dfdl.xsd)
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /c:/Users/wassj/Downloads/test-dfdl-workspace/jpeg.dfdl.xsd
```

**Comment by jw3** [comment]
I can check back later for another version to test.

**Comment by jw3** [comment]
Similar failure on the latest build.  I will get a development environment set up on this windows machine and try to give some better feedback.

**Comment by arosien** [comment]
> Similar failure on the latest build. I will get a development environment set up on this windows machine and try to give some better feedback.

Ugh. Sorry this is going on, and thanks for the help. I'll see how I can get access to a windows box somehow...

**Comment by arosien** [comment]
@jw3 can you post the exception you got? It _should_ be slightly different, but maybe I screwed up.

**Comment by jw3** [comment]
Looks like you got it, in the build I tested earlier.

1. VS Code claimed to have loaded -pre7
2. It did download -pre7 which I watched while it was being extracted in the xdg data dir
3. The console reported that -pre6 was the one that was run

I didn't notice 3 until I went back to copy the full output for your ask.

Should test that upgrade process a little more.  Maybe I missed a "reload required", could be.

Looks like you fixed this issue though.  Ill test on linux to make sure its working there.

**Comment by arosien** [comment]
> Looks like you got it, in the build I tested earlier.
> 
> 1. VS Code claimed to have loaded -pre7
> 2. It did download -pre7 which I watched while it was being extracted in the xdg data dir
> 3. The console reported that -pre6 was the one that was run
> 
> I didn't notice 3 until I went back to copy the full output for your ask.
> 
> Should test that upgrade process a little more. Maybe I missed a "reload required", could be.
> 
> Looks like you fixed this issue though. Ill test on linux to make sure its working there.

It's maybe not the best way to test the backend, but you can set `useExistingServer` to `true` in the `launch.json` and launch the backend directly from your dev env.

FYI I added some extra git versioning and build time metadata to the backend logging when it starts up, to help with knowing "what's really running".

**Comment by jw3** [comment]
OK, so tested some uninstall and reinstall of different vsix versions and the behavior is pretty consistent.  It is hard to believe I missed the easy to spot reload required boxes in multiple places, but that is the only explanation I have right now.

Tested on linux, also looks good.

**Review by jw3 — APPROVED** [review]
I tested -pre7 on windows and linux and it looks good.

**Pull request merged**
