### PR TITLE
Hex View Fix

### LINKED ISSUE #57: Reopen hex view
After the hex view is closed it should be able to be opened without restarting the debug.

### LINKED ISSUE #58: Hex view opens again after restarting the workspace
I would expect the hex view to be cleaned up after closing the debug session.  It is not cleaned up and even returns after workspace restart.

### Steps to reproduce
1. start a debug, hex view displayed
2. close ide
3. open ide
4. hex view is displayed

### PR DESCRIPTION
**Pull request by Shanedell**
- Fix issue where highlighted text and icon get stuck on a line, will now move down to the end of the file.
- Update location of data hex file so it can be reopened by the user if desired.
- Update extension to automatically close the hex file is already open in a visible editor, will also delete the data file if it exists, then opens the hex file once it is remade for the proper data file.
- Remove setting of white text color of selection

Closes #57 , Closes #58

### CODE REVIEW

**Comment by arosien** [comment]
It would be great to get this merged and cut into a release before tomorrow's demo!

**Comment by jw3** [comment]
@arosien Appears we might have an issue with Linux and XDG dirs, but it is a separate issue and not a blocker for this PR.  How do these changes look on your machine?

**Comment by jw3** [comment]
Tracking issue with arrow drawing and highlighting in #60

**Comment by arosien** [comment]
> @arosien Appears we might have an issue with Linux and XDG dirs, but it is a separate issue and not a blocker for this PR. How do these changes look on your machine?
> 
> (only mentioning because I cant easily test this PR because of the XDG isssue)

I pulled down the branch, but discovered I don't know how to launch the extension. I think I might need to install something locally?

```
> Executing task: yarn run watch <

yarn run v1.21.1
warning daffodil-debug@0.0.7: The engine "vscode" appears to be invalid.
$ webpack --watch --devtool nosources-source-map --info-verbosity verbose --config ./build/extension.webpack.config.js
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "/bin/zsh '-c', 'yarn run watch'" terminated with exit code: 127.

Terminal will be reused by tasks, press any key to close it.
```

?

**Comment by jw3** [comment]
The process I use is

1. Open the root project in VS Code
2. Run `yarn` from terminal to update deps
3. Press `F5` or go to the debug panel and run the `Extension` profile

**Comment by arosien** [comment]
> The process I use is
> 
> 1. Open the root project in VS Code
> 2. Run `yarn` from terminal to update deps
> 3. Press `F5` or go to the debug panel and run the `Extension` profile

Ah, thanks, I was missing the `yarn` step. Will add to the README.

**Comment by Shanedell** [comment]
Hey guys, got some downtime on vacation and saw the comments so I pushed a out a `v0.0.7-alpha` release that will have the changes there. this will just a temp release till the demo is over then can be deleted or if everything works okay for Adam, and its some linux issue or something, then you can delete it, merge and re-release a `v0.0.8` Also good luck tomorrow!!

**Pull request merged**
